### ISSUE TITLE
Change the shared key between Disputes and UserProfile from hash to arbitrableContractAddress

### ISSUE THREAD

**Issue by satello** [kleros/kleros-store#9]
The hash being stored right now is the arbitrableContractAddress anyways. The arbitrableContractAddress is a better unique key and is more inline with how the API works

**Comment by satello** [comment]
Updated shared key to be a compound key `arbitratorAddress` + `disputeId`

**Comment by felippenardi** [comment]
@n1c01a5 Can you close this issue since #11 solved it?
